name: Build

on: [push, pull_request]

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Checkout
      uses: actions/checkout@v3

    - uses: sparkfabrik/android-build-action@v1.5.0
      with:
        project-path: .
        output-path: traintastic-${{github.ref_name}}-${{github.run_number}}-${{env.CI_SHA_SHORT}}.apk
        ruby-version: "2.7.5"
        bundler-version: "2.3.26"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: traintastic-apk
        path: ${{github.workspace}}/*.apk

  deploy:
    name: Deploy to website
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [build-apk]

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: traintastic-apk
        path: ${{github.workspace}}/dist/${{env.CI_REF_NAME_SLUG}}/${{github.run_number}}

    - uses: easingthemes/ssh-deploy@v2.2.11
      env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/*"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{secrets.REMOTE_TARGET}}/traintastic-android/
  
